### PR TITLE
Update welcome.py

### PR DESCRIPTION
**Pull request by RishiAnand108**
Dynamic Separator: The separator now adjusts based on the terminal width for better responsiveness.

Stylized Text: Used a different font (slant) from pyfiglet to make the welcome message more visually appealing.

Modular Code: Added a main guard (if __name__ == "__main__":) to allow the script to be imported without running the welcome function immediately.

### CODE REVIEW

**Comment by RishiAnand108** [comment]
Sir please accept my pr and merge it .

**Review by zapdev360 — CHANGES_REQUESTED** [review]
Hi @RishiAnand108 ,
While I appreciate your idea of making the seperators dynamic, I'd still need you to align all such texts in the center of the terminal, including the welcome message and the texts following it up. You could do so using the `center()` method.

Adding on, calling `welcome()` in `welcome.py` isn't required, since we already have it imported in `main.py` and a block in there, to control the main execution flow.

**Comment by RishiAnand108** [comment]
Sir i have made the changes in file please review it once

**Review by zapdev360 — CHANGES_REQUESTED** [review]
@RishiAnand108 The "Cipherion" ascii art is still left aligned in the terminal.
I'd advise you to run and test your code before committing it.

**Review by RishiAnand108 — COMMENTED** [review]
In this version, the ASCII art is split into lines and each line is centered individually to ensure proper alignment within the terminal width. This should now display correctly.

**Review by RishiAnand108 — COMMENTED** [review]
Dynamically centers each part of the message based on the terminal's current width.
Uses separators (sep) that adjust to the full width.
Ensures pyfiglet-generated text and additional lines are aligned centrally.

**Review by zapdev360 — CHANGES_REQUESTED** [review]
Hi @RishiAnand108 ,
You're required to resolve conflicts and update your fork.

**Comment by RishiAnand108** [comment]
Sir now sorry as I have tried my all the way hard but I am now giving up on these .

**Pull request closed without merging**
