### PR TITLE
Added 2 more encryption techniques- TripleDES & Blowfish

### PR DESCRIPTION
**Pull request by pokymono**
Hey please check I have added 2 more techniques! @thelegendev

### CODE REVIEW

**Review by zapdev360 — COMMENTED** [review]
Hi @Rishitshivam ,

While I appreciate your efforts, there's an issue coming up since both of these algorithms are old.

- Algorithm deprecation warning:
> CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.al
gorithms.TripleDES and will be removed from this module in 48.0.0.

> CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.al
gorithms.Blowfish and will be removed from this module in 45.0.0.

Also, what's your opinion on `ChaCha20-Poly1305`? I think it's a decent choice, since `ChaCha20` serves for encryption and `Poly1305` checks for any alterations and authenticates it in the end, would server great when both of these are combined.

Don't be mistaken however, I'm still willing to keep `TripleDES` and `Blowfish` as other options, in case the user wants to use them.

**Comment by pokymono** [comment]
Yeah I also thought of having more stronger algorithms as options, ChaCha20-Poly1305 is cool and fast, sure I'll add them by tomorrow as another PR. For now you can merge these so I'll work on the masking feature on the updated repo

**Comment by diptodeepb** [comment]
Sure, appreciate the efforts.
Also, happy Diwali man! 🎉

**Comment by pokymono** [comment]
Happy Diwali to you too ! ❤️

**Pull request merged**
